### ISSUE TITLE
Make path to Catch2 configurable.

### ISSUE THREAD

**Issue by kevinsmia1939** [rcsb/mmtf-cpp#39]
From what I understand, the catch2 path is set here:

https://github.com/rcsb/mmtf-cpp/blob/407bf8e541530579b1f2c3e7f7fa96bb06ef5be9/CMakeLists.txt#L22

However, this make building mmtf with tests enable failed  when trying to make it a linux package, because it could not find catch2 dependency that was added to the linux package build recipe.

I build the package using openSUSE's build service.

https://build.opensuse.org/package/live_build_log/home:andythe_great/mmtf-cpp/openSUSE_Tumbleweed/x86_64

```
[   85s] ../tests/mmtf_tests.cpp:8:10: fatal error: catch.hpp: No such file or directory
[   85s]     8 | #include "catch.hpp"
[   85s]       |          ^~~~~~~~~~~
[   85s] compilation terminated. 
```

**Comment by gtauriello** [comment]
There was already a past effort for an openSUSE package with a similar issue here: https://github.com/rcsb/mmtf-cpp/issues/18#issuecomment-416917052

The tests and examples are meant for development and assume that you follow the commands [here](https://github.com/rcsb/mmtf-cpp#examples-and-tests) (incl. fetching Catch2 with `git submodule`). Neither tests nor examples nor Catch2 are needed to use this library...

**Comment by kevinsmia1939** [comment]
> There was already a past effort for an openSUSE package with a similar issue here: [#18 (comment)](https://github.com/rcsb/mmtf-cpp/issues/18#issuecomment-416917052)
> 
> The tests and examples are meant for development and assume that you follow the commands [here](https://github.com/rcsb/mmtf-cpp#examples-and-tests) (incl. fetching Catch2 with `git submodule`). Neither tests nor examples nor Catch2 are needed to use this library...

Thanks for reply. The openSUSE repo maintainer recommend the tests should be done if the test exist. So I think I will patch or some other will do it.
