### ISSUE TITLE
Could you please make a release to include commits fixing substantial bugs?

### ISSUE THREAD

**Issue by yurivict** [rcsb/mmtf-cpp#43]

**Comment by gtauriello** [comment]
@yurivict Am I correct to assume that you are referring to the bugfixes already available in the master branch? Or did you observe any new bugs?

I can make a release with the current version yes. I would like to point out though that I consider MMTF to be deprecated as a file format and BinaryCIF should be the preferred binary format. Accordingly I can only offer limited support for this project.

**Comment by yurivict** [comment]
> Or did you observe any new bugs?

No, only commits in the master branch.

**Comment by gtauriello** [comment]
The release v1.1.0 was generated: https://github.com/rcsb/mmtf-cpp/releases/tag/v1.1.0
