### ISSUE TITLE
bondOrderList should be optional wrt bondAtomList

### ISSUE THREAD

**Issue by danpf** [rcsb/mmtf-cpp#9]
https://github.com/rcsb/mmtf/blob/master/spec.md#bondorderlist

> Optional field If it exists bondAtomList must also be present. However bondAtomList may exist without bondOrderList.

https://github.com/rcsb/mmtf-cpp/blob/6e5749ac49e847aa41ac38c4ba51a43a20ffdebd/include/mmtf/structure_data.hpp#L530

have to add a check for `is default value` or `size == 0` before we check if they are consistent with each other.

**Comment by gtauriello** [comment]
Discussion on this was continued in PR #10.
